[package]
name = "odsynth"
version = "0.1.0"
description = "An open data synthesizer"
url = "https://github.com/kbaafi/data-synthesizer"

[author]
name = "Kofi Baafi"
email = "kbaafi@gmail.com"

[install_dependencies]
deps = ["toml","faker", "typer", "pandas"]

[entry_points]
scripts = [
    'synth=odsynth.entry_points.synth:main',
    'publish=odsynth.entry_points.publish:main',
]
