firstname:
  provider: first_name
lastname:
  provider: last_name
child:
  fields:
    firstname:
      provider: first_name
    lastname:
      provider: last_name
age:
  provider: random_int
  provider_args:
    min: 25
    max: 55
ssn:
  provider: com.github.kbaafi.us_ssn
about_me:
  provider: text
  provider_args:
    max_nb_chars: 50