fields:
  parent_firstname:
    provider: faker.first_name_male
    provider_args:
      locales: ["fi_FI"]
  parent_lastname:
    provider: faker.last_name
    provider_args:
      locales: ["fi_FI"]
  child:
    fields:
      firstname:
        provider: faker.first_name
      lastname:
        provider: faker.last_name
  parent_age:
    provider: faker.random_int
    provider_args:
      min: 25
      max: 55
  parent_ssn:
    provider: faker.ssn
  parent_about:
    provider: faker.text
    provider_args:
      max_nb_chars: 50
      locales: ["en_US"]
  ip_address:
    provider: faker.ipv4
