import os
import time
from typing import Any, Dict, List

from odsynth.transformers import JsonTransformer

from .abstract_writer import AbstractWriter


class JsonToDiscWriter(AbstractWriter):
    """Writers write generated data to JSON on disc"""

    def __init__(self, base_dir):
        """
        Constructor for JsonToDiscWriter

        Parameters
        -
        base_dir (str): Directory into which generated data is to be written
        """
        self._base_dir = base_dir
        self._transformer = JsonTransformer()

    def write_data(self, data: List[Dict[str, Any]]):
        """Writes generated data to JSON on Disc.

        Parameters:
        -
        data (list[dict]): Data generated by odsynth.DataGenerator
        """
        os.makedirs(self._base_dir, exist_ok=True)
        timestamp = int(time.time() * 1e6)
        filename = f"{self._base_dir}/odsynth_{timestamp}.json"
        with open(filename, "w") as file:
            for item in self._transformer.transform(data):
                file.write(item)
                file.write("\n")

    @classmethod
    def get_name(cls) -> str:
        return "json_to_disc"
