import os
import time
import xml.etree.ElementTree as ET
from typing import List
from xml.dom.minidom import parseString

from odsynth.transformers import XMLTransformer

from ..globals import DEFAULT_OUTPUT_SUBDIR, XML_DOC_ROOT
from .abstract_writer import AbstractWriter


class XMLToDiscWriter(AbstractWriter):
    def __init__(self, output_dir):
        """
        Constructor for XMLToDiscWriter

        Parameters
        -
        output_dir (str): Directory into which generated data is to be written
        """
        timestamp = int(time.time() * 1e6)
        if not output_dir:
            _output_dir = f"{os.getcwd()}/{DEFAULT_OUTPUT_SUBDIR}/xml/{timestamp}"
        else:
            _output_dir = f"{output_dir}/xml/{timestamp}"
        self._output_dir = _output_dir
        self._transformer = XMLTransformer()

    def write_data(self, data: List[str]):
        """Writes generated data to XML on Disc.

        Parameters:
        -
        data (list[dict]): Data generated by odsynth.DataGenerator
        """

        def pretty_xml(element: ET.Element):
            xml_string = ET.tostring(element, encoding="utf-8")
            return parseString(xml_string).toprettyxml(indent=" ")

        file_root = ET.Element(XML_DOC_ROOT)
        xml_str_list = self._transformer.transform(data)

        for xml_string in xml_str_list:
            element = ET.fromstring(xml_string)
            file_root.append(element)

        xml_doc = pretty_xml(file_root)

        os.makedirs(self._output_dir, exist_ok=True)
        timestamp = int(time.time() * 1e6)
        filename = f"{self._output_dir}/odsynth_{timestamp}.xml"
        with open(filename, "w") as file:
            file.write(xml_doc)

    @classmethod
    def get_name(cls) -> str:
        return "xml_to_disc"
